// The file ../speechAssets/customSlot_CANTEEN.txt will be generated by this list

module.exports = [
    {
        "verboseName": "Mensa Garching",
        "synonyms": [
            "mensa garching",
            "mensa in garching",
            "garching",
            "garching forschungszentrum",
            "mensa garching forschungszentrum",
            "garchinger mensa"
        ],
        "id": 139
    },
    {
        "verboseName": "Mensa Leopoldstraße",
        "synonyms": [
            "mensa leopoldstraße",
            "leopoldstraße",
            "mensa in der leopoldstraße",
            "mensa an der leopoldstraße"
        ],
        "id": 133
    },
    {
        "verboseName": "Mensa Arcisstraße",
        "synonyms": [
            "mensa arcisstraße",
            "arcisstraße",
            "stammgelände",
            "mensa stammgelände",
            "mensa am stammgelände",
            "mensa in der arcisstraße",
            "mensa bei der arcisstraße"],
        "id": 138
    },
    {
        "verboseName": "Mensa Martinsried",
        "synonyms": [
            "mensa martinsried",
            "martinsried",
            "mensa in martinsried"
        ],
        "id": 134
    },
    {
        "verboseName": "Mensa Großhadern",
        "synonyms": [
            "mensa großhadern",
            "großhadern",
            "mensa in großhadern",
            "mensa bei großhadern"
        ],
        "id": 135
    },
];

// ToDo: Other canteens
// 145 StuCafe Boltzmannstraße, Maschinenwesen
// 230 StuCafe Adalbertstraße
// 136 StuBistro Schellingstraße
// 232 StuCafe Karlstraße